// frontend/src/App.svelte
<script lang="ts">
  import { Route, Router} from "svelte-navigator";
  import HomePage from "./Page/HomePage.svelte";
  import { UserCookies } from "./lib/Cookies/User";
  import NoUserPage from "./Page/NoUserPage.svelte";
  import { user } from "./store/user";

</script>

{#if $user}
  <Router>
    <Route path="/" component={HomePage} />
  </Router>
{:else}
  <NoUserPage />
{/if}

// frontend/src/App.tsx
import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";
import "./App.css";
import Home from "./Page/Home";
import UserSelectorPage from "./Page/UserSelector";
import { UserCookies } from "./lib/User";

function App() {
  const user = UserCookies.getUser();
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/no-user" element={<UserSelectorPage />} />
      </Routes>
      {user ? (
        <Routes>
          <Route path="/" element={<Home />} />
        </Routes>
      ) : (
        <Navigate to={"/no-user"} />
      )}
    </BrowserRouter>
  );
}

export default App;
